name: "Run"
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  defaults:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - uses: pyodide/setup-emsdk@main

    - name: Verify
      run: emcc -v
  actions-use-cache-test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup emsdk (use cache if found, create otherwise)
        uses: pyodide/setup-emsdk@main
        with:
          version: 4.0.9
          actions-cache-folder: 'emsdk-cache-folder'
          no-cache: true

      - name: Verify
        run: emcc -v
  actions-use-cache-test-with-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Setup emsdk (use cache if found, create otherwise)
        uses: pyodide/setup-emsdk@main
        with:
          version: 4.0.9
          actions-cache-folder: 'emsdk-cache-folder'
          no-cache: false
  no-install:
    runs-on: ubuntu-latest
    steps:
      - uses: pyodide/setup-emsdk@main
        with:
          no-install: true

      - name: Verify
        run: emsdk list
  tot:
    runs-on: ubuntu-latest
    steps:
      - name: Setup emsdk (use cache if found, create otherwise)
        uses: pyodide/setup-emsdk@main
        with:
          version: tot
          no-cache: true
          update-tags: true

      - name: Verify
        run: emcc -v
